- name: Generate an empty temp file for CSR
  ansible.builtin.file:
    path: /tmp/admin.csr
    state: touch
    owner: root
    group: root
    mode: "0400"
  register: temp_file
- name: Generate Admin Operator private key
  community.crypto.openssl_privatekey:
    path: /vagrant/share/admin.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate Admin Operator CSR
  community.crypto.openssl_csr:
    path: "{{ temp_file.dest }}"
    privatekey_path: /vagrant/share/admin.key
    common_name: 'admin'
    subject:
      O: 'system:masters'
      OU: 'Kubernetes The Hard Way'
- name: Create Admin Operator TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /vagrant/share/admin.crt
    csr_path: "{{ temp_file.dest }}"
    privatekey_path: /vagrant/share/admin.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
