---
- name: Generate an empty temp file for CSR
  ansible.builtin.file:
    path: /tmp/ca.csr
    state: touch
    owner: root
    group: root
    mode: "0400"
  register: temp_file
- name: Generate CA private key
  community.crypto.openssl_privatekey:
    path: /vagrant/share/ca.key
    type: "{{ k8s_privatekey_type }}"
    state: present
- name: Generate CA CSR to provide ALT names and other options
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:TRUE
    common_name: kubernetes-ca
    keyUsage_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    path: "{{ temp_file.path }}"
    privatekey_path: /vagrant/share/ca.key
    state: present
- name: Generate CA certificate
  community.crypto.x509_certificate:
    path: /vagrant/share/ca.crt
    privatekey_path: /vagrant/share/ca.key
    csr_path: "{{ temp_file.path }}"
    provider: selfsigned
    state: present
- name: Copy cert to kubernetes PKI dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/pki/
    remote_src: true
    owner: root
    group: root
    mode: "0400"
  loop:
    - /vagrant/share/ca.crt
