- name: Generate an empty temp file for CSR
  ansible.builtin.file:
    path: /tmp/etcd-ca.csr
    state: touch
    owner: root
    group: root
    mode: "0400"
  register: temp_file
- name: Generate etcd CA private key
  community.crypto.openssl_privatekey:
    path: /vagrant/share/etcd-ca.key
    type: "{{ etcd_privatekey_type }}"
- name: Generate etcd CA CSR
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:TRUE
    common_name: etcd-ca
    keyUsage_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    path: "{{ temp_file.dest }}"
    privatekey_path: /vagrant/share/etcd-ca.key
    state: present
- name: Generate etcd CA certificate
  community.crypto.x509_certificate:
    path: /vagrant/share/etcd-ca.crt
    csr_path: "{{ temp_file.dest }}"
    privatekey_path: /vagrant/share/etcd-ca.key
    provider: selfsigned
    state: present
