- name: Reload k8s systemd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
- name: Restart kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: true
