---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: requirements-txt-fixer
      - id: check-yaml
        exclude: "{cilium,codedns}/files/manifests.yml"
      - id: sort-simple-yaml
      - id: check-added-large-files
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
          - --args=-write=true
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: terraform-validate
      # - id: tflint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        args:
          - --fix
          - .
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.28
    hooks:
      - id: checkov
      # - id: checkov_diff
      # - id: checkov_secrets
      # - id: checkov_container
      # - id: checkov_diff_container
      # - id: checkov_secrets_container
