---
- name: Enable IP Forwarding permanently
  ansible.builtin.copy:
    content: net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/20-ipforward.conf
    mode: "0644"
  notify: Reload sysctl
- name: Ensure python3-pip package is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: true
    cache_valid_time: "{{ cache_valid_time }}"
- name: Add current user to adm group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: adm
    append: true
- name: Ensure CA directory exists
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: "0700"
- name: Create private-network DNS records
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  with_items:
    - 192.168.56.2 node0 etcd-node0
    - 192.168.56.3 node1 etcd-node1
    - 192.168.56.4 node2 etcd-node2
  tags:
    - dns
