---
- name: Generate KubeConfig for Kubernetes components
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: /var/lib/kubernetes/{{ item }}.kubeconfig
    mode: "0640"
    owner: root
    group: root
  vars:
    kube_apiserver_address: localhost
    client_cert_path: /etc/kubernetes/pki/{{ item }}.crt
    client_key_path: /etc/kubernetes/pki/{{ item }}.key
  loop:
    - admin
- name: Generate KubeConfig for host machine
  ansible.builtin.template:
    src: kubeconfig.yml.j2
    dest: /vagrant/share/admin.yml
    mode: "0400"
  vars:
    kube_apiserver_address: "{{ hostvars[inventory_hostname].host_ip }}"
    ca_cert_path: ./ca.crt
    client_cert_path: ./admin.crt
    client_key_path: ./admin.key
  run_once: true
