- name: Ensure the etcd directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"
  loop:
    - /etc/kubernetes/pki/etcd
- name: Copy CA cert to machine
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/kubernetes/etcd/pki/
    owner: root
    group: root
    mode: "0640"
    remote_src: true
  loop:
    - /vagrant/share/etcd-ca.crt
