- name: Generate etcd server private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/etcd/kube-apiserver.key
    type: "{{ etcd_privatekey_type }}"
- name: Generate kube-apiserver server CSR
  community.crypto.openssl_csr:
    common_name: kube-apiserver
    extKeyUsage_critical: false
    extended_key_usage:
      - clientAuth
    path: /etc/kubernetes/pki/etcd/kube-apiserver.csr
    privatekey_path: /etc/kubernetes/pki/etcd/kube-apiserver.key
    subject_alt_name:
      - DNS:localhost
      - DNS:{{ etcd_peer_name }}
      - DNS:{{ inventory_hostname }}
      - IP:127.0.0.1
      - IP:{{ apiserver_ip }}
- name: Generate kube-apiserver certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/etcd/kube-apiserver.crt
    csr_path: /etc/kubernetes/pki/etcd/kube-apiserver.csr
    privatekey_path: /etc/kubernetes/pki/etcd/kube-apiserver.key
    provider: ownca
    state: present
    ownca_path: /vagrant/share/etcd-ca.crt
    ownca_privatekey_path: /vagrant/share/etcd-ca.key
    ownca_not_after: +365d
