- name: Generate etcd server private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/etcd/server.key
    type: "{{ etcd_privatekey_type }}"
- name: Generate etcd server CSR
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:FALSE
    common_name: etcd-server
    extKeyUsage_critical: false
    extended_key_usage:
      - clientAuth
      - serverAuth
    keyUsage_critical: true
    keyUsage:
      - digitalSignature
      - keyEncipherment
    path: /etc/kubernetes/pki/etcd/server.csr
    privatekey_path: /etc/kubernetes/pki/etcd/server.key
    subject_alt_name:
      - IP:127.0.0.1
      - IP:{{ hostvars[inventory_hostname].ansible_facts.all_ipv4_addresses | select('match', '^192.168.56') | first }}
      - DNS:localhost
      - DNS:{{ etcd_peer_name }}
      - DNS:{{ inventory_hostname }}
- name: Generate etcd server certificate
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/etcd/server.crt
    csr_path: /etc/kubernetes/pki/etcd/server.csr
    privatekey_path: /etc/kubernetes/pki/etcd/server.key
    provider: ownca
    state: present
    ownca_path: /vagrant/share/etcd-ca.crt
    ownca_privatekey_path: /vagrant/share/etcd-ca.key
    ownca_not_after: +365d
