- name: Generate control plane private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/apiserver.key
    type: Ed25519
- name: Generate control plane CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/apiserver.csr
    privatekey_path: /etc/kubernetes/pki/apiserver.key
    common_name: 'kube-apiserver'
    subject:
      O: 'system:masters'
      OU: 'Kubernetes The Hard Way'
- name: Create control plane TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/apiserver.crt
    csr_path: /etc/kubernetes/pki/apiserver.csr
    privatekey_path: /etc/kubernetes/pki/apiserver.key
    ownca_path: /etc/kubernetes/pki/ca.crt
    ownca_privatekey_path: /etc/kubernetes/pki/ca.key
    provider: ownca
    entrust_not_after: +365d
- name: Ensure /vagrant/certs/ exists
  ansible.builtin.file:
    path: /vagrant/certs/
    state: directory
    mode: "0700"
- name: Copy control plane TLS certificate to /vagrant/certs/
  ansible.builtin.copy:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /vagrant/certs/
    mode: "0600"
    remote_src: true
  loop:
    - apiserver.crt
    - apiserver.key
