- name: Generate Admin Operator private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/admin.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate Admin Operator CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/admin.csr
    privatekey_path: /etc/kubernetes/pki/admin.key
    common_name: 'admin'
    subject:
      O: 'system:masters'
      OU: 'Kubernetes The Hard Way'
- name: Create Admin Operator TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/admin.crt
    csr_path: /etc/kubernetes/pki/admin.csr
    privatekey_path: /etc/kubernetes/pki/admin.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
- name: Copy Admin Operator TLS certificate to /vagrant/share/
  ansible.builtin.copy:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /vagrant/share/
    mode: "0400"
    remote_src: true
  loop:
    - admin.crt
    - admin.key
