- name: Ensure CA directory exists
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    state: directory
    mode: "0750"
- name: Generate API Server private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-apiserver.key
    type: "{{ privatekey_type }}"
- name: Generate API Server CSR
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:FALSE
    common_name: kube-apiserver
    extKeyUsage_critical: false
    extended_key_usage:
      - clientAuth
      - serverAuth
    keyUsage:
      - digitalSignature
      - keyEncipherment
    keyUsage_critical: true
    path: /etc/kubernetes/pki/kube-apiserver.csr
    privatekey_path: /etc/kubernetes/pki/kube-apiserver.key
    subject:
      O: system:masters
      OU: Kubernetes The Hard Way
    subject_alt_name:
      - IP:127.0.0.1
      - IP:{{ ansible_facts.all_ipv4_addresses[-1] }}
      - IP:{{ ansible_facts.all_ipv6_addresses[-1] }}
      - DNS:localhost
      - DNS:{{ inventory_hostname }}
      - DNS:kubernetes
      - DNS:kubernetes.default
      - DNS:kubernetes.default.svc
      - DNS:kubernetes.default.svc.cluster
      - DNS:kubernetes.default.svc.cluster.local
- name: Create API Server TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-apiserver.crt
    csr_path: /etc/kubernetes/pki/kube-apiserver.csr
    privatekey_path: /etc/kubernetes/pki/kube-apiserver.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    ownca_not_after: +365d
    provider: ownca
  retries: 120
  delay: 5
  register: cert
  until: cert is succeeded
- name: Ensure /vagrant/share/ exists
  ansible.builtin.file:
    path: /vagrant/share/
    state: directory
    mode: "0755"
- name: Copy API Server TLS certificate to /vagrant/share/
  ansible.builtin.copy:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /vagrant/share/
    mode: "0640"
    remote_src: true
  loop:
    - kube-apiserver.crt
    - kube-apiserver.key
