- name: Generate controller manager private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-controller-manager.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate controller manager CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-controller-manager.csr
    privatekey_path: /etc/kubernetes/pki/kube-controller-manager.key
    common_name: 'system:kube-controller-manager'
    subject:
      O: 'system:kube-controller-manager'
      OU: 'Kubernetes The Hard Way'
- name: Create controller manager TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-controller-manager.crt
    csr_path: /etc/kubernetes/pki/kube-controller-manager.csr
    privatekey_path: /etc/kubernetes/pki/kube-controller-manager.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
