- name: Generate kube-proxy private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-proxy.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate kube-proxy CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-proxy.csr
    privatekey_path: /etc/kubernetes/pki/kube-proxy.key
    common_name: "system:kube-proxy"
    subject:
      O: "system:node-proxier"
      OU: "Kubernetes The Hard Way"
    subject_alt_name:
      - IP:{{ host_ip }}
      - DNS:{{ inventory_hostname }}
- name: Create kube-proxy TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-proxy.crt
    csr_path: /etc/kubernetes/pki/kube-proxy.csr
    privatekey_path: /etc/kubernetes/pki/kube-proxy.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
