- name: Generate kubelet private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kubelet.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate kubelet CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kubelet.csr
    privatekey_path: /etc/kubernetes/pki/kubelet.key
    common_name: 'system:node:{{ inventory_hostname }}'
    subject:
      O: 'system:nodes'
      OU: 'Kubernetes The Hard Way'
    subject_alt_name:
      - IP:{{ host_ip }}
      - DNS:{{ inventory_hostname }}
- name: Create kubelet TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kubelet.crt
    csr_path: /etc/kubernetes/pki/kubelet.csr
    privatekey_path: /etc/kubernetes/pki/kubelet.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
