- name: Generate Scheduler private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/kube-scheduler.key
    type: "{{ k8s_privatekey_type }}"
- name: Generate Scheduler CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/kube-scheduler.csr
    privatekey_path: /etc/kubernetes/pki/kube-scheduler.key
    common_name: 'system:kube-scheduler'
    subject:
      O: 'system:kube-scheduler'
      OU: 'Kubernetes The Hard Way'
- name: Create Scheduler TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/kube-scheduler.crt
    csr_path: /etc/kubernetes/pki/kube-scheduler.csr
    privatekey_path: /etc/kubernetes/pki/kube-scheduler.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
