- name: Ensure CA directory exists
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    state: directory
    mode: "0750"
- name: Generate Service Account private key
  community.crypto.openssl_privatekey:
    path: /etc/kubernetes/pki/serviceaccount.key
    type: "{{ privatekey_type }}"
- name: Generate Service Account CSR
  community.crypto.openssl_csr:
    path: /etc/kubernetes/pki/serviceaccount.csr
    privatekey_path: /etc/kubernetes/pki/serviceaccount.key
    common_name: 'service-accounts'
    subject:
      O: 'system:masters'
      OU: 'Kubernetes The Hard Way'
- name: Create Service Account TLS certificate using CA key and cert
  community.crypto.x509_certificate:
    path: /etc/kubernetes/pki/serviceaccount.crt
    csr_path: /etc/kubernetes/pki/serviceaccount.csr
    privatekey_path: /etc/kubernetes/pki/serviceaccount.key
    ownca_path: /vagrant/share/ca.crt
    ownca_privatekey_path: /vagrant/share/ca.key
    provider: ownca
    ownca_not_after: +365d
  retries: 120
  delay: 5
  register: cert
  until: cert is succeeded
- name: Ensure /vagrant/share/ exists
  ansible.builtin.file:
    path: /vagrant/share/
    state: directory
    mode: "0755"
- name: Copy Service Account TLS certificate to /vagrant/share/
  ansible.builtin.copy:
    src: /etc/kubernetes/pki/{{ item }}
    dest: /vagrant/share/
    mode: "0640"
    remote_src: true
  loop:
    - serviceaccount.crt
    - serviceaccount.key
