- name: Create systemd service
  ansible.builtin.template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/etcd.service"
    mode: "0644"
    owner: root
    group: root
  notify: Reload etcd-gateway systemd
- name: Start etcd service
  ansible.builtin.systemd_service:
    name: etcd.service
    state: started
    enabled: true
    daemon_reload: true
