- name: Ensure Kubernetes config dir exists
  ansible.builtin.file:
    path: /etc/kubernetes/config
    state: directory
    mode: "0755"
    owner: root
    group: root
- name: Copy configurations
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - src: kube-scheduler.conf.yml
      dest: /etc/kubernetes/config/kube-scheduler.yml
- name: Copy API server systemd service files
  ansible.builtin.template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
    mode: "0644"
    owner: root
    group: root
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
- name: Start all the services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
