- name: Copy API server systemd service files
  ansible.builtin.template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
    mode: "0644"
    owner: root
    group: root
  loop:
    - kube-apiserver
    - kube-controller-manager
- name: Start all the services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
    daemon_reload: true
  loop:
    - kube-apiserver
    - kube-controller-manager
