---
- name: Install Kubernetes
  ansible.builtin.import_tasks:
    file: install.yml
- name: Configure Kubernetes
  ansible.builtin.import_tasks:
    file: configure.yml
- name: Configure Kubelet
  ansible.builtin.import_tasks:
    file: kubelet.yml
- name: Configure Kube proxy
  ansible.builtin.import_tasks:
    file: kube-proxy.yml
