- name: Ensure CNI directory exists
  ansible.builtin.file:
    path: /etc/cni/net.d/
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Configure CNI Networking
  ansible.builtin.copy:
    content: |
      {
        "cniVersion": "1.0.0",
        "name": "containerd-net",
        "plugins": [
          {
            "type": "bridge",
            "bridge": "cni0",
            "isGateway": true,
            "ipMasq": true,
            "promiscMode": true,
            "ipam": {
              "type": "host-local",
              "ranges": [
                [{
                  "subnet": "{{ pod_subnet_cidr_v4 }}"
                }],
                [{
                  "subnet": "{{ pod_subnet_cidr_v6 }}"
                }]
              ],
              "routes": [
                { "dst": "0.0.0.0/0" },
                { "dst": "::/0" }
              ]
            }
          },
          {
            "type": "portmap",
            "capabilities": {"portMappings": true}
          }
        ]
      }
    dest: /etc/cni/net.d/10-containerd-net.conf
    owner: root
    group: root
    mode: "0640"
- name: Ensure containerd directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Get containerd default config
  ansible.builtin.command: containerd config default
  changed_when: false
  register: containerd_default_config
- name: Configure containerd
  ansible.builtin.copy:
    content: "{{ containerd_default_config.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0640"
