- name: Download containerd
  ansible.builtin.get_url:
    url: "{{ containerd_url }}"
    dest: "{{ downloads_dir }}"
    checksum: "sha256:{{ lookup('url', containerd_checksum_url) | split | first }}"
    mode: "0444"
  register: containerd_download
  tags:
    - download
- name: Create /tmp/containerd directory
  ansible.builtin.file:
    path: /tmp/containerd
    state: directory
    mode: "0755"
- name: Extract containerd
  ansible.builtin.unarchive:
    src: "{{ containerd_download.dest }}"
    dest: /tmp/containerd
    mode: "0755"
    remote_src: true
- name: Glob files in unarchived bin directory
  ansible.builtin.find:
    paths: /tmp/containerd
    file_type: file
    recurse: true
    mode: "0755"
  register: containerd_bin_files
- name: Install containerd
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  loop: "{{ containerd_bin_files.files | map(attribute='path') | list }}"
- name: Download containerd service
  ansible.builtin.get_url:
    url: "{{ containerd_service_url }}"
    dest: /etc/systemd/system/
    mode: "0644"
    owner: root
    group: root
  tags:
    - download
