- name: Download crictl
  ansible.builtin.get_url:
    url: "{{ crictl_url }}"
    dest: /tmp/
    mode: "0764"
    checksum: "sha256:{{ lookup('url', crictl_checksum_url) | split | first }}"
  register: crictl_download
- name: Extract crictl binary
  ansible.builtin.unarchive:
    src: "{{ crictl_download.dest }}"
    dest: /usr/local/bin/
    remote_src: true
    mode: "0755"
