- name: Download kubelet
  ansible.builtin.get_url:
    url: "{{ kubelet_url }}"
    dest: /usr/local/bin/kubelet
    owner: root
    group: root
    mode: "0755"
    checksum: "sha256:{{ lookup('url', kubelet_checksum_url) | split | first }}"
