- name: Prepare
  ansible.builtin.import_tasks:
    file: prepare.yml
- name: Install containerd
  ansible.builtin.import_tasks:
    file: containerd.yml
- name: Install runc
  ansible.builtin.import_tasks:
    file: runc.yml
- name: Install cni-plugins
  ansible.builtin.import_tasks:
    file: cni-plugins.yml
- name: Install kubectl
  ansible.builtin.import_tasks:
    file: kubectl.yml
- name: Install kubelet
  ansible.builtin.import_tasks:
    file: kubelet.yml
- name: Configure CNI
  ansible.builtin.import_tasks:
    file: cni-config.yml
- name: Finalize configuration
  ansible.builtin.import_tasks:
    file: finalize.yml
