---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name:
      - conntrack
      - ipset
      - socat
    state: present
    update_cache: true
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0
