- name: Download runc
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: /usr/local/bin/runc
    mode: "0755"
    use_proxy: false
    checksum: "sha256:{{ runc_checksum }}"
  when: runc_url.endswith('runc.amd64')
