- name: Download helm
  ansible.builtin.get_url:
    url: "{{ helm_download_url }}"
    checksum: "sha256:{{ helm_checksum }}"
    dest: "{{ downloads_dir }}/{{ helm_download_url | basename }}"
    owner: root
    group: root
    mode: "0444"
  tags:
    - download
  register: helm_download
- name: Extract helm
  ansible.builtin.unarchive:
    src: "{{ helm_download.dest }}"
    dest: /usr/local/bin/
    remote_src: true
    extra_opts:
      - --strip-components=1
      - --wildcards
      - "**/helm"
- name: Add cilium repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    state: present
- name: Copy cilium values file
  ansible.builtin.template:
    src: values.yml.j2
    dest: /tmp/cilium-values.yml
    owner: root
    group: root
    mode: "0444"
- name: Install cilium
  kubernetes.core.helm:
    chart_version: "{{ cilium_version }}"
    release_name: cilium
    release_namespace: kube-system
    release_state: present
    chart_ref: cilium/cilium
    update_repo_cache: true
    values_files:
      - /tmp/cilium-values.yml
    wait: true
    purge: true
    atomic: true
    history_max: 10
    timeout: 2m
  tags:
    - helm
