- name: Copy manifests.yml
  ansible.builtin.copy:
    src: "manifests.yml"
    dest: /tmp/manifests.yml
- name: Apply Cilium manifests
  kubernetes.core.k8s:
    state: present
    src: /tmp/manifests.yml
